/* u7_api.h generated by valac 0.56.17, the Vala compiler, do not modify */

#ifndef __U7_API_H__
#define __U7_API_H__

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <json-glib/json-glib.h>
#include <float.h>
#include <math.h>
#include <gee.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_U7_OBJECT (u7_object_get_type ())
#define U7_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_OBJECT, U7Object))
#define U7_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_OBJECT, U7ObjectClass))
#define IS_U7_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_OBJECT))
#define IS_U7_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_OBJECT))
#define U7_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_OBJECT, U7ObjectClass))

typedef struct _U7Object U7Object;
typedef struct _U7ObjectClass U7ObjectClass;
typedef struct _U7ObjectPrivate U7ObjectPrivate;

#define TYPE_U7_PROPERTY_LIST (u7_property_list_get_type ())
#define U7_PROPERTY_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_PROPERTY_LIST, U7PropertyList))
#define U7_PROPERTY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_PROPERTY_LIST, U7PropertyListClass))
#define IS_U7_PROPERTY_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_PROPERTY_LIST))
#define IS_U7_PROPERTY_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_PROPERTY_LIST))
#define U7_PROPERTY_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_PROPERTY_LIST, U7PropertyListClass))

typedef struct _U7PropertyList U7PropertyList;
typedef struct _U7PropertyListClass U7PropertyListClass;

#define TYPE_U7_DICTIONARY (u7_dictionary_get_type ())
#define U7_DICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_DICTIONARY, U7Dictionary))
#define U7_DICTIONARY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_DICTIONARY, U7DictionaryClass))
#define IS_U7_DICTIONARY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_DICTIONARY))
#define IS_U7_DICTIONARY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_DICTIONARY))
#define U7_DICTIONARY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_DICTIONARY, U7DictionaryClass))

typedef struct _U7Dictionary U7Dictionary;
typedef struct _U7DictionaryClass U7DictionaryClass;

#define TYPE_APP_DELEGATE (app_delegate_get_type ())
#define APP_DELEGATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_DELEGATE, AppDelegate))
#define APP_DELEGATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_DELEGATE, AppDelegateClass))
#define IS_APP_DELEGATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_DELEGATE))
#define IS_APP_DELEGATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_DELEGATE))
#define APP_DELEGATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_DELEGATE, AppDelegateClass))

typedef struct _AppDelegate AppDelegate;
typedef struct _AppDelegateClass AppDelegateClass;
typedef struct _AppDelegatePrivate AppDelegatePrivate;

#define TYPE_U7_OBJECT_EXTRAS (u7_object_extras_get_type ())
#define U7_OBJECT_EXTRAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_OBJECT_EXTRAS, U7ObjectExtras))
#define U7_OBJECT_EXTRAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_OBJECT_EXTRAS, U7ObjectExtrasClass))
#define IS_U7_OBJECT_EXTRAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_OBJECT_EXTRAS))
#define IS_U7_OBJECT_EXTRAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_OBJECT_EXTRAS))
#define U7_OBJECT_EXTRAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_OBJECT_EXTRAS, U7ObjectExtrasClass))

typedef struct _U7ObjectExtras U7ObjectExtras;
typedef struct _U7ObjectExtrasClass U7ObjectExtrasClass;
typedef struct _U7ObjectExtrasPrivate U7ObjectExtrasPrivate;
typedef void (*U7ObjectU7MethodHandler) (U7Object* _self_, U7PropertyList* arg, gpointer user_data);
typedef struct _U7PropertyListPrivate U7PropertyListPrivate;

#define TYPE_U7_STRING (u7_string_get_type ())
#define U7_STRING(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_STRING, U7String))
#define U7_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_STRING, U7StringClass))
#define IS_U7_STRING(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_STRING))
#define IS_U7_STRING_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_STRING))
#define U7_STRING_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_STRING, U7StringClass))

typedef struct _U7String U7String;
typedef struct _U7StringClass U7StringClass;
typedef struct _U7StringPrivate U7StringPrivate;

#define TYPE_U7_NUMBER (u7_number_get_type ())
#define U7_NUMBER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_NUMBER, U7Number))
#define U7_NUMBER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_NUMBER, U7NumberClass))
#define IS_U7_NUMBER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_NUMBER))
#define IS_U7_NUMBER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_NUMBER))
#define U7_NUMBER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_NUMBER, U7NumberClass))

typedef struct _U7Number U7Number;
typedef struct _U7NumberClass U7NumberClass;
typedef struct _U7NumberPrivate U7NumberPrivate;
typedef enum  {
	U7_NUMBER_NUMBER_TYPE_INT,
	U7_NUMBER_NUMBER_TYPE_DOUBLE,
	U7_NUMBER_NUMBER_TYPE_BOOL
} U7NumberNumberType;

#define U7_NUMBER_TYPE_NUMBER_TYPE (u7_number_number_type_get_type ())

#define TYPE_U7_ARRAY (u7_array_get_type ())
#define U7_ARRAY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_ARRAY, U7Array))
#define U7_ARRAY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_ARRAY, U7ArrayClass))
#define IS_U7_ARRAY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_ARRAY))
#define IS_U7_ARRAY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_ARRAY))
#define U7_ARRAY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_ARRAY, U7ArrayClass))

typedef struct _U7Array U7Array;
typedef struct _U7ArrayClass U7ArrayClass;
typedef struct _U7ArrayPrivate U7ArrayPrivate;
typedef struct _U7DictionaryPrivate U7DictionaryPrivate;

#define TYPE_U7_DATE (u7_date_get_type ())
#define U7_DATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_DATE, U7Date))
#define U7_DATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_DATE, U7DateClass))
#define IS_U7_DATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_DATE))
#define IS_U7_DATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_DATE))
#define U7_DATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_DATE, U7DateClass))

typedef struct _U7Date U7Date;
typedef struct _U7DateClass U7DateClass;
typedef struct _U7DatePrivate U7DatePrivate;

#define TYPE_U7_UTILITY (u7_utility_get_type ())
#define U7_UTILITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_UTILITY, U7Utility))
#define U7_UTILITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_UTILITY, U7UtilityClass))
#define IS_U7_UTILITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_UTILITY))
#define IS_U7_UTILITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_UTILITY))
#define U7_UTILITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_UTILITY, U7UtilityClass))

typedef struct _U7Utility U7Utility;
typedef struct _U7UtilityClass U7UtilityClass;
typedef struct _U7UtilityPrivate U7UtilityPrivate;

#define TYPE_U7_DATA (u7_data_get_type ())
#define U7_DATA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_U7_DATA, U7Data))
#define U7_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_U7_DATA, U7DataClass))
#define IS_U7_DATA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_U7_DATA))
#define IS_U7_DATA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_U7_DATA))
#define U7_DATA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_U7_DATA, U7DataClass))

typedef struct _U7Data U7Data;
typedef struct _U7DataClass U7DataClass;
typedef struct _U7DataPrivate U7DataPrivate;

#define TYPE_U7_ERROR (u7_error_get_type ())

struct _U7Object {
	GObject parent_instance;
	U7ObjectPrivate * priv;
};

struct _U7ObjectClass {
	GObjectClass parent_class;
	gchar* (*get_name) (U7Object* self);
	void (*publishOnThread) (U7Object* self, const gchar* name, U7Dictionary* info);
	void (*invoke_method) (U7Object* self, const gchar* method_name, U7PropertyList* arg);
	gchar* (*to_string) (U7Object* self);
};

struct _AppDelegate {
	U7Object parent_instance;
	AppDelegatePrivate * priv;
};

struct _AppDelegateClass {
	U7ObjectClass parent_class;
};

struct _U7ObjectExtras {
	GObject parent_instance;
	U7ObjectExtrasPrivate * priv;
	guint64 thread_id;
	GPtrArray* observers;
	GPtrArray* subscriptions;
};

struct _U7ObjectExtrasClass {
	GObjectClass parent_class;
};

struct _U7PropertyList {
	U7Object parent_instance;
	U7PropertyListPrivate * priv;
};

struct _U7PropertyListClass {
	U7ObjectClass parent_class;
	U7PropertyList* (*deep_copy) (U7PropertyList* self);
	JsonNode* (*to_json) (U7PropertyList* self);
};

struct _U7String {
	U7PropertyList parent_instance;
	U7StringPrivate * priv;
};

struct _U7StringClass {
	U7PropertyListClass parent_class;
};

struct _U7Number {
	U7PropertyList parent_instance;
	U7NumberPrivate * priv;
};

struct _U7NumberClass {
	U7PropertyListClass parent_class;
};

struct _U7Array {
	U7PropertyList parent_instance;
	U7ArrayPrivate * priv;
};

struct _U7ArrayClass {
	U7PropertyListClass parent_class;
};

struct _U7Dictionary {
	U7PropertyList parent_instance;
	U7DictionaryPrivate * priv;
};

struct _U7DictionaryClass {
	U7PropertyListClass parent_class;
};

struct _U7Date {
	U7PropertyList parent_instance;
	U7DatePrivate * priv;
};

struct _U7DateClass {
	U7PropertyListClass parent_class;
};

struct _U7Utility {
	GTypeInstance parent_instance;
	volatile int ref_count;
	U7UtilityPrivate * priv;
};

struct _U7UtilityClass {
	GTypeClass parent_class;
	void (*finalize) (U7Utility *self);
};

struct _U7Data {
	U7PropertyList parent_instance;
	U7DataPrivate * priv;
};

struct _U7DataClass {
	U7PropertyListClass parent_class;
};

typedef enum  {
	U7_ERROR_INVALID_FORMAT
} U7Error;
#define U7_ERROR u7_error_quark ()

VALA_EXTERN GType u7_object_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Object, g_object_unref)
VALA_EXTERN GType u7_property_list_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7PropertyList, g_object_unref)
VALA_EXTERN GType u7_dictionary_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Dictionary, g_object_unref)
VALA_EXTERN GType app_delegate_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (AppDelegate, g_object_unref)
VALA_EXTERN AppDelegate* app_delegate_new (void);
VALA_EXTERN AppDelegate* app_delegate_construct (GType object_type);
VALA_EXTERN GType u7_object_extras_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7ObjectExtras, g_object_unref)
VALA_EXTERN U7ObjectExtras* u7_object_extras_new (void);
VALA_EXTERN U7ObjectExtras* u7_object_extras_construct (GType object_type);
VALA_EXTERN gchar* u7_object_get_name (U7Object* self);
VALA_EXTERN void u7_object_setExtras (U7Object* self,
                          U7ObjectExtras* e);
VALA_EXTERN void u7_object_publishOnThread (U7Object* self,
                                const gchar* name,
                                U7Dictionary* info);
VALA_EXTERN void u7_object_publish (U7Object* self,
                        const gchar* name,
                        U7Dictionary* info);
VALA_EXTERN void u7_object_addSubscription (U7Object* self,
                                const gchar* sub);
VALA_EXTERN void u7_object_removeSubscription (U7Object* self,
                                   const gchar* sub);
VALA_EXTERN void u7_object_setThreadID (U7Object* self,
                            guint64 tid);
VALA_EXTERN GPtrArray* u7_object_getSubscriptions (U7Object* self);
VALA_EXTERN GPtrArray* u7_object_getObservers (U7Object* self);
VALA_EXTERN guint64 u7_object_getThreadID (U7Object* self);
VALA_EXTERN void u7_object_subscribe (U7Object* self,
                          const gchar* method_name,
                          U7ObjectU7MethodHandler handler,
                          gpointer handler_target);
VALA_EXTERN void u7_object_invoke_method (U7Object* self,
                              const gchar* method_name,
                              U7PropertyList* arg);
VALA_EXTERN void u7_object_perform (U7Object* self,
                        const gchar* method_name,
                        U7PropertyList* arg);
VALA_EXTERN void u7_object_init (void);
VALA_EXTERN guint64 u7_object_uuid (U7Object* self);
VALA_EXTERN U7Object* u7_object_new (void);
VALA_EXTERN U7Object* u7_object_construct (GType object_type);
VALA_EXTERN gchar* u7_object_to_string (U7Object* self);
VALA_EXTERN gint u7_object_get_instance_count (void);
VALA_EXTERN gint u7_object_get_class_instance_count (const gchar* class_name);
VALA_EXTERN gchar* u7_object_get_class_name (U7Object* self);
VALA_EXTERN gchar* u7_object_get_all_class_instance_counts_report (void);
VALA_EXTERN GType u7_string_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7String, g_object_unref)
VALA_EXTERN U7String* u7_string_new (const gchar* value);
VALA_EXTERN U7String* u7_string_construct (GType object_type,
                               const gchar* value);
VALA_EXTERN const gchar* u7_string_get_value (U7String* self);
VALA_EXTERN GType u7_number_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Number, g_object_unref)
VALA_EXTERN GType u7_number_number_type_get_type (void) G_GNUC_CONST ;
VALA_EXTERN U7Number* u7_number_new_from_int (gint value);
VALA_EXTERN U7Number* u7_number_construct_from_int (GType object_type,
                                        gint value);
VALA_EXTERN U7Number* u7_number_new_from_double (gdouble value);
VALA_EXTERN U7Number* u7_number_construct_from_double (GType object_type,
                                           gdouble value);
VALA_EXTERN U7Number* u7_number_new_from_bool (gboolean value);
VALA_EXTERN U7Number* u7_number_construct_from_bool (GType object_type,
                                         gboolean value);
VALA_EXTERN gint u7_number_as_int (U7Number* self);
VALA_EXTERN gdouble u7_number_as_double (U7Number* self);
VALA_EXTERN gboolean u7_number_as_bool (U7Number* self);
VALA_EXTERN U7Number* u7_number_new (void);
VALA_EXTERN U7Number* u7_number_construct (GType object_type);
VALA_EXTERN U7NumberNumberType u7_number_get_number_type (U7Number* self);
VALA_EXTERN GType u7_array_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Array, g_object_unref)
VALA_EXTERN U7Array* u7_array_new (GeeArrayList* value);
VALA_EXTERN U7Array* u7_array_construct (GType object_type,
                             GeeArrayList* value);
VALA_EXTERN GeeArrayList* u7_array_get_value (U7Array* self);
VALA_EXTERN U7Dictionary* u7_dictionary_new (GeeHashMap* value);
VALA_EXTERN U7Dictionary* u7_dictionary_construct (GType object_type,
                                       GeeHashMap* value);
VALA_EXTERN void u7_dictionary_add_pairs (U7Dictionary* self,
                              const gchar* first_key,
                              U7PropertyList* first_value,
                              ...);
VALA_EXTERN U7Dictionary* u7_dictionary_with_pairs (const gchar* first_key,
                                        U7PropertyList* first_value,
                                        ...);
VALA_EXTERN GeeHashMap* u7_dictionary_get_value (U7Dictionary* self);
VALA_EXTERN GType u7_date_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Date, g_object_unref)
VALA_EXTERN U7Date* u7_date_new (GDateTime* value);
VALA_EXTERN U7Date* u7_date_construct (GType object_type,
                           GDateTime* value);
VALA_EXTERN GDateTime* u7_date_get_value (U7Date* self);
VALA_EXTERN gpointer u7_utility_ref (gpointer instance);
VALA_EXTERN void u7_utility_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_u7_utility (const gchar* name,
                                   const gchar* nick,
                                   const gchar* blurb,
                                   GType object_type,
                                   GParamFlags flags);
VALA_EXTERN void value_set_u7_utility (GValue* value,
                           gpointer v_object);
VALA_EXTERN void value_take_u7_utility (GValue* value,
                            gpointer v_object);
VALA_EXTERN gpointer value_get_u7_utility (const GValue* value);
VALA_EXTERN GType u7_utility_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Utility, u7_utility_unref)
VALA_EXTERN gchar* u7_utility_getStringFromDictionaryForKey (U7Object* obj,
                                                 const gchar* key);
VALA_EXTERN gchar* u7_utility_get_type_name (GType t_type,
                                 GBoxedCopyFunc t_dup_func,
                                 GDestroyNotify t_destroy_func,
                                 gconstpointer instance);
VALA_EXTERN U7Utility* u7_utility_new (void);
VALA_EXTERN U7Utility* u7_utility_construct (GType object_type);
VALA_EXTERN GType u7_data_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (U7Data, g_object_unref)
VALA_EXTERN U7Data* u7_data_new (GBytes* value);
VALA_EXTERN U7Data* u7_data_construct (GType object_type,
                           GBytes* value);
VALA_EXTERN GBytes* u7_data_get_value (U7Data* self);
VALA_EXTERN U7PropertyList* u7_property_list_construct (GType object_type);
VALA_EXTERN U7PropertyList* u7_property_list_deep_copy (U7PropertyList* self);
VALA_EXTERN JsonNode* u7_property_list_to_json (U7PropertyList* self);
VALA_EXTERN GQuark u7_error_quark (void);
VALA_EXTERN GType u7_error_get_type (void) G_GNUC_CONST ;
VALA_EXTERN U7PropertyList* u7_property_list_parse_json_string (const gchar* json_string,
                                                    GError** error);
VALA_EXTERN U7PropertyList* u7_property_list_from_json (JsonNode* node,
                                            GError** error);
VALA_EXTERN gchar* u7_property_list_to_json_string (U7PropertyList* self);
VALA_EXTERN U7Dictionary* u7_property_list_test_dictionary (void);

G_END_DECLS

#endif
